### ISSUE TITLE
Create a game board

### ISSUE THREAD

**Issue by mariaalouisaa** [mariaalouisaa/snake-the-game#3]
There should be a gameboard area on the screen.

**Comment by mariaalouisaa** [comment]
Completed in merge #2.
Decided to go with The Graphics Canvas element as I have no previous experience using this. Let the challenge commence!

**Comment by alternadiva** [comment]
I've read through your code and experimented with the UI and it works perfectly and looks (and sounds) so cool. 🤩

---

https://github.com/mariaalouisaa/snake-the-game/blob/c971e36aa565792a9361238fa7aace8b2167269e/index.js#L10
I haven't encountered the canvas html element before and it's functioning so well and interesting to see all the properties you can modify with it.

---

https://github.com/mariaalouisaa/snake-the-game/blob/c971e36aa565792a9361238fa7aace8b2167269e/index.js#L113-L121
Probably it's only temporary, but I felt the movement of the snake a bit slow even for level 1, starting with a tiny bit faster speed may be better

---

https://github.com/mariaalouisaa/snake-the-game/blob/c971e36aa565792a9361238fa7aace8b2167269e/index.js#L108-L109
Also, thank you for the detailed comments, they made it so much easier to understand the code

---

Well done, Maria, you've done an amazing job so far! 👏✨  (Even, motivated me to start my project finally 😅)
